cookie:
  expiry_days: 30
  key: npro
  name: npro
credentials:
  usernames:
    ? ''
    : name: ''
      password: $2b$12$vcWwRgRGRjFeTFmb6kVb0Okpmbo753VSaeC456V2dsCdsjU9sKcm2
    migue:
      name: Migue
      password: $2b$12$UO6h.IRljes8e14DkJFfjuILiXz.uZ.AbiKfp24oD7P03AO5aycme
    milomorales:
      name: milomorales
      password: $2b$12$ap7EFtTNmxe9Ji6XjCbsh.J5zqf55Wp2hap5f99yqy4y10sV61wAy
